\version "2.18.2"

\header {
  title = "toc-en-ata"
  composer = "Generated by Markoviser."
}

\score
{
  \new Staff
  {
    \tempo 4=120
    \key c \major
    \clef treble
{ ais''16 g''16 a''16 a''16 a''16 ais''16 g''16 e''16 f''16 a''16 d''16 f''16 g''16 a''16 ais''16 g''16 a''16 g''16 a''16 ais''16 g''16 ais''16 g''16 a''16 a''16 d''16 f''16 g''16 f''16 e''16 g''16 e''16 f''16 a''16 d''16 g'16 a'16 g'16 a'16 g'16 f'16 g'16 f'16 g'16 ais'16 e'16 cis'16 ais'16 c''16 f'16 cis'16 a16 g16 a16 cis'16 ais'16 a'16 c''16 d''16 g'16 f'16 cis'16 ais'16 d''16 e''16 f''16 g''16 e''16 cis''16 d''16 e''16 g''16 ais''16 g''16 a''16 a''16 ais''16 e''16 cis''16 d''16 e''16 cis''16 d''16 f''16 ais'16 a'16 ais'16 e'16 g'16 ais'16 e'16 cis'16 e'16 g'16 a'16 c''16 e''16 a'16 c''16 d''16 cis''16 d''16 f''16 g''16 ais''16 g''16 a''16 g''16 e''16 cis''16 d''16 e''16 cis''16 d''16 f''16 g''16 ais''16 g''16 ais''16 g''16 c''16 d''16 g'16 f'16 g'16 f'16 a'16 ais'16 e'16 g'16 ais'16 e'16 f'16 a'16 d'16 f'16 cis'16 ais'16 a'16 g'16 f'16 g'16 f'16 g'16 f'16 a'16 d'16 f'16 g'16 ais'16 e'16 d'16 cis'16 e'16 f'16 g'16 a'16 c''16 d''16 f''16 g''16 c''16 d''16 f''16 a''16 ais''16 g''16 a''16 d''16 cis''16 d''16 e''16 cis''16 d''16 f''16 ais'16 e'16 g'16 f'16 cis'16 a16 g16 a16 cis'16 a16 cis'16 ais'16 c''16 e''16 f''16 g''16 ais''16 g''16 ais''16 g''16 ais''16 g''16 a''16 d''16 e''16 cis''16 d''16 e''16 cis''16 d''16 f''16 g''16 f''16 a''16 g''16 e''16 f''16 g''16 ais''16 g''16 e''16 a'16 c''16 d''16 f''16 e''16 cis''16 d''16 g'16 a'16 cis''16 d''16 f''16 g''16 e''16 cis''16 d''16 f''16 g''16 e''16 cis''16 d''16 g'16 f'16 g'16 a'16 g'16 cis'16 e'16 d'16 f'16 g'16 e'16 f'16 a'16 c''16 d''16 f''16 ais'16 a'16 ais'16 } \\ 
  } % Staff


  \layout {
    \context { \RemoveEmptyStaffContext }
  }
  \midi { }
} % score